# Generated by Django 4.1.3 on 2023-02-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=7)),
                ('panel', models.CharField(max_length=7)),
                ('mouse_enter', models.CharField(max_length=7)),
                ('mouse_click', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Colores',
                'db_table': 'COLORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'DETALLE_DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=255)),
                ('es_factura', models.IntegerField()),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('por_pagar', models.IntegerField()),
            ],
            options={
                'db_table': 'DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogStockPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_antiguo', models.IntegerField()),
                ('stock_agregado', models.IntegerField()),
                ('precio_antiguo', models.IntegerField()),
                ('precio_nuevo', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'LOG_STOCK_PRECIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id_paleta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_paleta', models.CharField(max_length=50)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'PALETA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_barra', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoDescartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_descartado', models.IntegerField()),
            ],
            options={
                'db_table': 'PRODUCTO_DESCARTADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('razon_social', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeqFolio',
            fields=[
                ('nuevo_folio', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Secuencia folios',
                'db_table': 'SEQ_FOLIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'TRABAJADOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('tipo_venta', models.CharField(db_collation='utf8_spanish_ci', max_length=255)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'VENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor_total', models.IntegerField()),
            ],
            options={
                'db_table': 'VENTA_PRODUCTO',
                'managed': False,
            },
        ),
    ]
